version: "3.2"
services:

  cloud-db:
    image: tpi-mon-db
    volumes:
      - "./mock-tpi-state.json:/mock-tpi-state.json"

  cloud-redis:
    image: redis:4.0

  cloud:
    image: tpi-mon-cloud
    ports:
      - 9753:9753
    links:
      - cloud-db:db
      - cloud-redis:redis
    environment:
      - "Tpimon.Cloud.DBHost=db"


  local:
    image: tpi-mon-local
    links:
      - mock:mock
      - cloud:cloud
      - local-redis:redis
    environment:
      - Tpimon.Local.TPIHost=mock
      - Tpimon.Local.TPIPassword=mock123
      - Tpimon.Local.CloudWSURL=ws://cloud:9754/ws
      - Tpimon.Local.CloudToken=cloud123
    ports:
      - 9752:9752
    volumes:
      - "./local-config.json:/root/.config/tpi-mon/Local.json"

  local-redis:
    image: redis:4.0

  mock:
    image: tpi-mon-mock
    volumes:
      - "./mock-tpi-state.json:/mock-tpi-state.json"
    environment:
      - "Tpimon.Mock.StateFilePath=/mock-tpi-state.json"
    ports:
      - 9751:9751

